### ISSUE TITLE
Does this really work now?

### ISSUE THREAD

**Issue by eos1d3** [iambluedev1/cfscrape-java#3]
It does not work for me. Any idea?
My code in main:

```
CfScrape cfScrape = CfScrape.get();
cfScrape.setUrl("a torrent site url");
String html = cfScrape.getSyncHtml();
System.out.println(html);
```

```
Exception in thread "main" com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.net.ConnectException: Connection refused (Connection refused)
	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3159)
	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3111)
	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3176)
	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3081)
	at fr.iambluedev.cfscrape.core.http.DirectRequest.getResponse(DirectRequest.java:32)
	at fr.iambluedev.cfscrape.core.CfScrape.getSyncHtml(CfScrape.java:55)
	at Torrents.main(FreeTorrents.java:62)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at com.github.kevinsawicki.http.HttpRequest.openOutput(HttpRequest.java:2728)
	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3151)
	... 6 more

```

**Comment by iambluedev1** [comment]
Hi, 

This exception may happen when the website you're looking for or the api url are down. Check both. 
If your torrent url is reachable, the problem comes from the api which may be unreachable. 

The api can be found here : https://github.com/iambluedev1/cfscrape-api , and you need to add : "cfScrape.setApiHost("url of the api");" in your java code before getting any response.

**Comment by eos1d3** [comment]
Hi, 
The torrent url is reachable. After adding `cfScrape.setApiHost("url of the api")` in my code, I have to run the cfscrape-api, right? this is what I did not do. I just realised it does not use Java builtin HTTP server for port listening.

Will try later. Thanks a lot!
